import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "./_providers/ReactQuery";
import { PrivyProvider } from "./_providers/PrivyProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  bio,
  // casts,
  display
}: Readonly<{
  children: React.ReactNode;
  bio: React.ReactNode;
  // casts: React.ReactNode;
  display: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-4`}
      >
        <PrivyProvider>
          <ReactQueryProvider>
            {children}
            <div>
              <h2 className="text-medium text-3xl">Settings</h2>
              {bio}
              {display}
            </div>

            {/* Rate limits the shit {casts} */}
          </ReactQueryProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
